# This is the build configuration for Netlify

[build]
  # This command creates the config.js file during the build process
  # It uses the environment variables you will set in the Netlify UI.
  command = "echo 'window.firebaseConfig = { apiKey: \"$FIREBASE_API_KEY\", authDomain: \"$FIREBASE_AUTH_DOMAIN\", projectId: \"$FIREBASE_PROJECT_ID\", storageBucket: \"$FIREBASE_STORAGE_BUCKET\", messagingSenderId: \"$FIREBASE_MESSAGING_SENDER_ID\", appId: \"$FIREBASE_APP_ID\", measurementId: \"$FIREBASE_MEASUREMENT_ID\" };' > config.js"
  
  # This tells Netlify which folder to publish. Since your index.html is in the root,
  # we set it to the current directory ".".
  publish = "."

